## Required
configs:
  state_s3_bucket: lambda-dk-s3-bucket
  role_arn: Basic-Lambda-Role
  function_name: add_function

## Required
handler_config:
  timeout: 60
  memory_size: 128

## Required (Only Uppercase)
tags:
  Env: test

## Required (Only Uppercase)
envs:
  var_A: 10
  var_B: 20
